### ISSUE TITLE
Reconnect after each publish??

### ISSUE THREAD

**Issue by MrGibbage** [Oyatel/CometD.NET#12]
I took the sample code and modified it a bit

https://gist.github.com/1611728

What I have seen is that if I start this program twice, and connect on each one, and then hit the publish button, both get the published text. But if I hit the publish button again, the only the one that published it will see it. I have to hit connect again, even though the client does still seem to be connected. I have tried adding the connect code to the end of the receiving text code, but that didn't help. I think I need a lesson on how comet works. How am I supposed to be able to keep on sending data back and forth?

**Comment by grEvenX** [comment]
Please, can you provide a working GIST URL so I can see the code.
The one you posted is not working...

**Comment by MrGibbage** [comment]
https://gist.github.com/1611728

Sorry about that...

Original post corrected too.

.

On Sun, Jan 15, 2012 at 3:17 PM, grEvenX <
reply@reply.github.com

**Comment by grEvenX** [comment]
I'm a bit puzzled by the code, why do you want to create a new client when receiving message from the chat/skip channel?

**Comment by MrGibbage** [comment]
OK, now I feel like an idiot. I added that code yesterday to see if I
needed to reconnect a new client after each message. That did not help.

So, I just now went back to run it again so I could tell you what I was
seeing, step-by-step. Well, now it is working. I guess I was seeing things
yesterday.

You may close this issue. But I will have some more questions soon. Is this
the best place to post them?
.

On Sun, Jan 15, 2012 at 4:28 PM, grEvenX <
reply@reply.github.com

**Comment by grEvenX** [comment]
Closing the issue, I'm not too familiar with github as well, but posting the messages here works for me for now :P
