### ISSUE TITLE
Silverlight-enabled library

### ISSUE THREAD

**Issue by apetrozzelli** [Oyatel/CometD.NET#2]
Hi,
first of all thanks for your effort.
I was wondering if you have plans to release a Silverlight-enabled version of the CometD.NET library.

Many thanks,
Alessandro

**Comment by grEvenX** [comment]
We don't have any experience with Silverlight, and we currently have no plans for adding the feature ourselves. That also makes it hard for me to judge what it would take of resources to make it "Silverlight-enabled".
Everyone is of course welcome to contribute to the project by forking/pulling our code.
