### ISSUE TITLE
Reconnection issue

### ISSUE THREAD

**Issue by srkamineni** [Oyatel/CometD.NET#3]
After the server goes down, the .net client is not reconnecting at all.  My understanding was that it clients will try to reconnect after the server goes down.

Or is there any thing that we can do to reconnect. 

Thanks
Raj

**Comment by grEvenX** [comment]
Thanks for the observation Raj. This is the responsibility of the library for sure, and I'm pretty sure we tested this well on our end.
How are you able to confirm that it does not "reconnect" ?
It should reconnect to the server, but the question might be what is happending for subscribtions etc.

**Comment by srkamineni** [comment]
Well, after the server went down and came back up, the client never received any messages from the server.   I had to restart my .net client to connect back again and start getting the messages.  

I am wondering if I am missing some addition of a listener - like disconnect and then connect again.  What do you suggest.

Raj

**Comment by guruprasad83** [comment]
@srkamineni - Even am facing the same issue - `Well, after the server went down and came back up, the client never received any messages from the server. I had to restart my .net client to connect back again and start getting the messages.`
Did you get any solution for this? Am also using .net client

**Comment by ohaucke** [comment]
@guruprasad83 
I've implemented an extension which raises an event if the connection got closed by the server.
You could check the `message` in `rcvMeta` and modify the code to match your response and raise the event.

```cs
using Cometd.Bayeux;
using Cometd.Bayeux.Client;
using System;

namespace Foobar.Utilities
{
    public class LoggingExtension : IExtension
    {
        private static NLog.Logger logger = NLog.LogManager.GetLogger("Foobar");

        public event EventHandler ConnectionError;

        public bool rcv(IClientSession session, IMutableMessage message)
        {
            return true;
        }

        public bool rcvMeta(IClientSession session, IMutableMessage message)
        {
            if (message.Successful)
            {
                logger.Debug(message.JSON);
            }

            if (message.ContainsKey("exception"))
            {
                logger.Fatal(message["exception"]);
            }

            if (message.ContainsKey("error"))
            {
                logger.Error(message["error"]);
                if (message["error"].ToString().ToLower() == "403::unknown client")
                {
                    this.OnConnectionError();
                }
            }

            return true;
        }

        public bool send(IClientSession session, IMutableMessage message)
        {
            return true;
        }

        public bool sendMeta(IClientSession session, IMutableMessage message)
        {
            return true;
        }

        private void OnConnectionError()
        {
            this.ConnectionError?.Invoke(this, new EventArgs());
        }
    }
}
```

Afterwards you need to add the extension to your bayeuxClient and subscribe to the event where you can re-establish the connection
```cs
LoggingExtension loggingExtension = new LoggingExtension();
loggingExtension.ConnectionError += loggingExtension_ConnectionError;
bayeuxClient.addExtension(loggingExtension);
```

**Comment by swagathchandra** [comment]
@ohaucke - Can you please share code for extension. I am facing the same issue

**Comment by ohaucke** [comment]
@swagathchandra I already posted it (`LoggingExtension`)

**Comment by nahoj28** [comment]
Hi @ohaucke , Thanks for the information. It is very helpfull for me, however I'm not sure of understand what is the steps to add into the EventHanlder (loggingExtension_ConnectionError). Should I connect  to the instance again into the handler? or into the hanlder only is needed subscribe to the channels again?

**Comment by ohaucke** [comment]
Hi @nahoj28, sorry that is way in the past, so i don't remember it but from the code, i would say you need to completely reconnect because the accesstoken isn't valid anymore.
