### ISSUE TITLE
Publish after disconnect

### ISSUE THREAD

**Issue by iainxt** [Oyatel/CometD.NET#9]
Hi,

I am using this client with Cometd, and I have noticed that sometimes the client publishes after it disconnects. I am using the example code, so I know it is publishing before it calls disconnect.

I have had a look at the code, however its currently over my head. Any ideas how this can happen?

Cheers,

Iain

**Comment by magnusga** [comment]
Hello,

I tested (and made a small update to) the example code (in README.TXT). It seems to work fine. Are there any long timeouts between your client and server? Are you using the java cometd-server?

Magnus.

**Comment by grEvenX** [comment]
Will close this bug missing a response. Please open it again if you have checked the questions in the last comment and still have issues.
